# Generated by Django 4.2 on 2023-05-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('L', 'Letter'), ('I', 'Internship')], default='I', max_length=1),
        ),
    ]
