# Generated by Django 4.2 on 2023-05-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_province_internship_logo_internship_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='title',
        ),
    ]
