# Generated by Django 4.2 on 2023-05-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_internship_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting'), ('R', 'Rejected'), ('A', 'Approved'), ('Z', 'Archived')], max_length=1),
        ),
    ]
