# Generated by Django 4.2 on 2023-05-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, choices=[('S', 'Sent'), ('G', 'Got')], max_length=1, null=True),
        ),
    ]
