# Generated by Django 4.2 on 2023-05-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting'), ('R', 'Rejected'), ('P', 'Pending'), ('A', 'Accepted')], max_length=1),
        ),
    ]
